enum RateLimiterType {
  FIXED_WINDOW_COUNTER = 'FIXED_WINDOW_COUNTER',
  LEAKING_BUCKET = 'LEAKING_BUCKET',
  SLIDING_WINDOW_COUNTER = 'SLIDING_WINDOW_COUNTER',
  SLIDING_WINDOW_LOG = 'SLIDING_WINDOW_LOG',
  TOKEN_BUCKET = 'TOKEN_BUCKET',
}

export { RateLimiterType };
